# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('price', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('timeT', models.CharField(max_length=50)),
                ('timeU', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile', models.URLField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Seller'),
        ),
    ]
