# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='profile',
            field=models.URLField(),
        ),
    ]
